//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaLib.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFiyatTanim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFiyatTanim()
        {
            this.tblStokFiyat = new HashSet<tblStokFiyat>();
        }
    
        public int ID { get; set; }
        public string FiyatKodu { get; set; }
        public string FiyatAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokFiyat> tblStokFiyat { get; set; }
    }
}
