//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaLib.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKDVTanim
    {
        public int ID { get; set; }
        public int KDVKodu { get; set; }
        public string Aciklama { get; set; }
    }
}
