//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaLib.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStokAyar
    {
        public int ID { get; set; }
        public string StokKodu { get; set; }
        public Nullable<bool> PasifStok { get; set; }
        public Nullable<bool> SatisYapilmaz { get; set; }
        public Nullable<bool> AlisYapilmaz { get; set; }
        public Nullable<bool> SiparisYok { get; set; }
        public Nullable<bool> TeklifYok { get; set; }
        public Nullable<bool> TalepYok { get; set; }
    
        public virtual tblStok tblStok { get; set; }
    }
}
