//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaLib.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStokGrup
    {
        public int ID { get; set; }
        public string StokKodu { get; set; }
        public string GrupKodu { get; set; }
        public string Deger { get; set; }
    
        public virtual tblStok tblStok { get; set; }
        public virtual tblStokGrupTanim tblStokGrupTanim { get; set; }
    }
}
