//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaLib.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStok()
        {
            this.tblStokAyar = new HashSet<tblStokAyar>();
            this.tblStokFiyat = new HashSet<tblStokFiyat>();
            this.tblStokGrup = new HashSet<tblStokGrup>();
        }
    
        public int ID { get; set; }
        public string StokKodu { get; set; }
        public string StokAdi { get; set; }
        public Nullable<int> AlisKDVOrani { get; set; }
        public Nullable<int> SatisKDVOrani { get; set; }
        public string OlcuBr { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokAyar> tblStokAyar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokFiyat> tblStokFiyat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokGrup> tblStokGrup { get; set; }
    }
}
