//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaLib.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SzrBaseEntities : DbContext
    {
        public SzrBaseEntities()
            : base("name=SzrBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFiyatTanim> tblFiyatTanim { get; set; }
        public virtual DbSet<tblKDVTanim> tblKDVTanim { get; set; }
        public virtual DbSet<tblStok> tblStok { get; set; }
        public virtual DbSet<tblStokFiyat> tblStokFiyat { get; set; }
        public virtual DbSet<tblStokGrup> tblStokGrup { get; set; }
        public virtual DbSet<tblStokGrupDetay> tblStokGrupDetay { get; set; }
        public virtual DbSet<tblStokGrupTanim> tblStokGrupTanim { get; set; }
        public virtual DbSet<tblTableColDefs> tblTableColDefs { get; set; }
        public virtual DbSet<tblStokAyar> tblStokAyar { get; set; }
        public virtual DbSet<ViewStokFiyat> ViewStokFiyat { get; set; }
        public virtual DbSet<ViewStokGrup> ViewStokGrup { get; set; }
    }
}
